### ISSUE TITLE
Can I set a proxy per registry?

### ISSUE THREAD

**Issue by cmoreno** [junosuarez/npm-delegate#1]
I have a private and a public registry. My private registry is behind an intranet so I need to be in the company VPN to access it (no proxy), however, in order to access the public registry, I need to set a proxy. Can I achieve this with npm-delegate?

**Comment by junosuarez** [comment]
`npm-delegate` uses Node's [http module](http://nodejs.org/api/http.html#http_http_request_options_callback) - so if your proxy supports HTTP basic auth, then it will work. However, if it uses something like a SOCKS proxy, that's not currently supported, although I would entertain a pull request.

`npm-delegate` uses [fallback](https://npmjs.org/package/fallback) to handle retry logic, you might be able to script what you need that way. I haven't used any of these, but a quick search for [SOCKS modules](https://npmjs.org/browse/keyword/socks) turns up some good options.
