### ISSUE TITLE
Publish the binary-creating version to npm

### ISSUE THREAD

**Issue by nomiddlename** [junosuarez/npm-delegate#5]
The version of npm-delegate in npm doesn't have the "bin" section in the package.json that the github version has. This confused me for a while, trying to work out why npm hadn't created the symlink when I installed npm-delegate globally.

**Comment by junosuarez** [comment]
I've republished as 0.1.0 in npm (and also updated the tag to 64f7bd36c9d7d21f5be8907ea88d34be3b46e7f5)

**Comment by nomiddlename** [comment]
Thanks - I've confirmed that it installs ok now.
